# Define version
version: 1

# Define your URLs (Mandatory!)
# URLs should start with - (remove the comment symbol #)
# Replace the values with your tokens/ids
# For example a telegram URL would look like:
#- tgram://1839738127:AAFlQ4xkuW328uD71XugxQATTKMnoWF_CoA/1829562397
urls:
   - tgram://1839738127:AAFlQ4xkuW328uD71XugxQATTKMnoWF_CoA/1829562397
  # - discord://WebhookID/WebhookToken/
  # - slack://tokenA/tokenB/tokenC
  # More options here: https://github.com/caronc/apprise
